"""initial migration

Revision ID: 379d3ec51731
Revises: 
Create Date: 2026-05-12 10:24:55.892548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel

# revision identifiers, used by Alembic.
revision: str = '379d3ec51731'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_name'), 'hospital', ['name'], unique=True)
    op.create_table('procedure',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_name'), 'procedure', ['name'], unique=True)
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registration', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_registration'), 'user', ['registration'], unique=True)
    op.create_table('log',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('performed', 'observed', 'assistant', 'supervised', 'training', name='roleenum'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('procedure_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_clock', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_hospital_id'), 'log', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_log_procedure_id'), 'log', ['procedure_id'], unique=False)
    op.create_index(op.f('ix_log_user_id'), 'log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_user_id'), table_name='log')
    op.drop_index(op.f('ix_log_procedure_id'), table_name='log')
    op.drop_index(op.f('ix_log_hospital_id'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_user_registration'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_procedure_name'), table_name='procedure')
    op.drop_table('procedure')
    op.drop_index(op.f('ix_hospital_name'), table_name='hospital')
    op.drop_table('hospital')
    # ### end Alembic commands ###
